fuel_app:
  container_name: "fuel_app"
  build: ./app
  restart: always
  env_file: ./app/env
  links:
    - fuel_mysql:db
  volumes:
    - /var/run
    - ./php-el-training:/usr/src/app
    - ./app/php-fpm.d:/usr/local/etc/php-fpm.d

fuel_nginx:
  container_name: "fuel_nginx"
  build: ./nginx
  restart: always
  ports:
    - "80:80"
  links:
    - fuel_app:app
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/application.conf:/etc/nginx/conf.d/application.conf
  volumes_from:
    - fuel_app

fuel_mysql:
  container_name: "fuel_mysql"
  build: ./mysql
  restart: always
  ports:
    - "3306:3306"
  volumes_from:
    - fuel_storage

fuel_storage:
  build: ./storage
